[[pages]]
path = "Main_Menu.py"
name = "Home"
icon = ":house:"

[[pages]]
name = "Content Generation Apps"
icon = ":lower_left_fountain_pen:"
is_section = true

[[pages]]
path = "./pages/Product_Metadata_Generator.py"
name = "Product Metadata Generator"
icon = "âš™ï¸"

[[pages]]
path = "pages/Product_Review_Summarizer.py"
name = "Product Review Summarizer"
icon = "ğŸ“–"

[[pages]]
path = "pages/Document_FAQ_Generator.py"
name = "Doument FAQ Generator"
icon = "â‰ï¸"

[[pages]]
path = "pages/Product_Blog_Writer.py"
name = "Product Blog Writer"
icon = "ğŸ“ï¸"

[[pages]]
name = "Chatbot apps"
icon = ":robot_face:"
is_section = true

[[pages]]
path = "pages/Claude_3_Chatbot.py"
name = "Claude 3 Chatbot"
icon = "ğŸ’¬"

